spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/catshop}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        default_batch_fetch_size: 1000
    show-sql: true
  docker:
    compose:
      lifecycle-management: start-only
  flyway:
    baseline-on-migrate: true
    
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      MemberCustomerUnique: MEMBER_CUSTOMER_UNIQUE
      ProductCategoryUnique: PRODUCT_CATEGORY_UNIQUE
      OrderMemberUnique: ORDER_MEMBER_UNIQUE
      OrderDeliveryUnique: ORDER_DELIVERY_UNIQUE

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /docs
    disable-swagger-default-url: true
    display-request-duration: true
